[ServerInfo]
;Key Active lien he nha cung cap
KeyEncDec = "B7BDBCA8BF"
//===========================
//-- Common
//===========================
CustomerName = Estafadorfiles
ClientVersion = 1.04.05
ClientSerial = DjGamer2022
AntihackPort = 55858
;Port dùng để GS kết nối tới, Port này không cần mở Online, port chỉ sử dụng trong local
XShieldGSPort = 50112
;Thời gian Block khi phát hiện hack 
;Tính bằng giây
DetectionLockTime = 3000
;Của sổ tối đa trên 1 máy
MaxGameInstances = 2
MaxIpConnection = 10
;Tự động kết nối lại
ReconnectSwitch = 1

//===========================
//-- Launcher
//===========================
LauncherName = Launcher.exe
LauncherCRC = 0
//===========================
//-- EncDec (Mã Hoá Kết Nối Game Client)
//===========================
EncDecKey1 = 0
EncDecKey2 = 0
EncDecSetNumber = 0
;==================================================
; AntiFlood Settings
;Switch On/Off
;MinTime : kết nối dưới Giây  sẽ ghi nhận CountFlood
;MaxTime : kết nối trên Giây sẽ tự động UnBlock
;MaxCount : nếu liên tục kết nối dưới MinTime = MaxCount thì Block
;BlockTime : Giây Block IP
;==================================================
AntiFloodSwitch = 1
AntiFloodMinTimeCheck = 1
AntiFloodMaxTimeCheck = 5
AntiFloodMaxCount = 150
AntiFloodBlockTime = 60
//=== Chức năng ghi Dump lại khi phát hiện 
;= 1 Check HANDLE & INJECT
;= 2 Check Window List
;= 4 Check BadWord
;Type trên nếu phát hiện sẽ ghi Dump, cộng các số lại để sử dụng nhiều loại 
;VD : muốn add dump khi check inject và bad word AddDump =5 thì khi phát hiện 1 trong 2 loại sẽ tự  add Dump
MemoryAddDumpDB = 1
;Switch On/Off ngăn chặn sử dụng máy ảo 
VirtualMachineSwitch = 0
InternalVersion = 0
;Chức phát hiện Edit Memory
;Switch On/Off
MemoryGuardSwitch = 0
MemoryMaxHandle = 6
;1 = Check HANDLE
;2 = Check INJECT
;3 = Check HANDLE & INJECT
MemoryGuardNumber = 2
//===============================
;Chức năng Check Macro (Auto Key)
;Switch On/Off
;Number Lv Check (Max 5) càng cao càng gắt
MacroProtectSwitch = 0
MacroProtectNumber = 0
//===========================
//-- Memory (Can't be changed)
//===========================
MemoryAddress1 = 0x00E611B2
MemoryAddress2 = 0x00E61F68
MemoryAddress3 = 0x00E61F70
MemoryAddress4 = 0x08793718
MemoryAddress5 = 0x08128AC8
MemoryAddress6 = 0x00E8C578
MemoryAddress7 = 0xC4E70EDF
MemoryAddress8 = 0xC4E6F2B9
//===========================
//-- FTP: Upload snapshot when detecting hack
//===========================
[FTPInfo]
FTPSwitch = 0
IpAddress = 
Port = 
Username = 
Password = 
//===========================
//-- Discord (PREMIUM FEATURES)
//===========================
[Discord]
DiscordSwitch = 0
DiscordID = 0
HackLogSwitch = 0