"""
Translate ALL .bmd files and their TXT sources in CHN folder.
Handles mixed UTF-8/GBK encoding in source files.
"""
import os, re, sys

CHN_DIR = r'E:\MU\ClientFile\Data\Local\CHN'
ITEM_TXT = r'E:\MU\MuServer\4.GameServer\Sub 1\Data\Item\Item.txt'
KEY = [0xFC, 0xCF, 0xAB]

# ============================================================
# COMPREHENSIVE VN→CN TRANSLATION DICTIONARY
# ============================================================
VN_CN_MAP = {}

def add_map(vn, cn):
    VN_CN_MAP[vn] = cn

# === Common game terms ===
add_map('tấn công', '攻击')
add_map('phòng thủ', '防御')
add_map('sức mạnh', '力量')
add_map('nhanh nhẹn', '敏捷')
add_map('thể lực', '体力')
add_map('năng lượng', '能量')
add_map('sát thương', '伤害')
add_map('yêu cầu', '需求')
add_map('cấp độ', '等级')
add_map('kỹ năng', '技能')
add_map('phép thuật', '魔法')
add_map('tốc độ', '速度')
add_map('kháng', '抗性')
add_map('hồi phục', '恢复')
add_map('máu', '生命值')
add_map('vũ khí', '武器')
add_map('giáp', '盔甲')
add_map('khiên', '盾牌')
add_map('mũ', '头盔')
add_map('áo', '铠甲')
add_map('quần', '护腿')
add_map('găng', '手套')
add_map('giầy', '靴子')
add_map('ủng', '靴子')
add_map('nhẫn', '戒指')
add_map('dây chuyền', '项链')
add_map('cánh', '翅膀')
add_map('ngọc', '宝石')
add_map('cụm', '簇')
add_map('trái tim', '心脏')
add_map('sức đánh', '攻击力')
add_map('ma lực', '魔法力')
add_map('sức tấn công', '攻击力')
add_map('sức phòng thủ', '防御力')
add_map('chính xác', '命中')
add_map('né tránh', '闪避')
add_map('độ bền', '耐久度')
add_map('tỉ lệ', '几率')
add_map('xác suất', '概率')
add_map('tăng', '增加')
add_map('giảm', '减少')
add_map('tối đa', '最大')
add_map('tối thiểu', '最小')
add_map('thấp nhất', '最低')
add_map('cao nhất', '最高')
add_map('của', '的')
add_map('và', '和')
add_map('sự kiện', '活动')
add_map('nhiệm vụ', '任务')
add_map('chiến đấu', '战斗')
add_map('cường hóa', '强化')
add_map('hợp thành', '合成')
add_map('phân giải', '分解')
add_map('trao đổi', '交换')
add_map('vật phẩm', '物品')
add_map('trang bị', '装备')
add_map('thông thường', '普通')
add_map('cao cấp', '高级')
add_map('đặc biệt', '特殊')
add_map('huy chương', '勋章')
add_map('bảng xếp hạng', '排行榜')
add_map('xếp hạng', '排行')
add_map('kỵ sĩ', '骑士')
add_map('hiệp sĩ', '骑士')
add_map('chiến binh', '战士')
add_map('pháp sư', '法师')
add_map('phù thủy', '巫师')
add_map('tiên nữ', '精灵')
add_map('đấu sĩ', '斗士')
add_map('chúa tể', '领主')
add_map('thánh nữ', '圣女')
add_map('ma thuật', '魔法')
add_map('cấp', '级')

# === Item tooltips ===
add_map('Lực 1 tay:', '单手攻击力:')
add_map('Lực 2 tay:', '双手攻击力:')
add_map('Số lượng:', '数量:')
add_map('Phòng thủ:', '防御力:')
add_map('Sức kháng phép:', '魔法抗性:')
add_map('Né tránh:', '闪避:')
add_map('Tốc độ tấn công:', '攻击速度:')
add_map('Tốc dộ di chuyển:', '移动速度:')
add_map('Tốc độ di chuyển:', '移动速度:')
add_map('Độ bền:', '耐久度:')
add_map('Cấp độ yêu cầu:', '需要等级:')
add_map('Sức mạnh yêu cầu:', '需要力量:')
add_map('Nhanh nhẹn yêu cầu:', '需要敏捷:')
add_map('Thể lực yêu cầu:', '需要体力:')
add_map('Năng lượng yêu cầu:', '需要能量:')
add_map('Mệnh lệnh yêu cầu:', '需要统率:')
add_map('Sức đánh:', '攻击力:')
add_map('Tăng sức tấn công', '增加攻击力')
add_map('Tăng tốc độ bơi', '增加游泳速度')
add_map('Tăng tốc độ di chuyển', '增加移动速度')
add_map('Tăng sức sát thương', '增加伤害力')
add_map('Tăng %% phép thuật', '增加%%魔法')
add_map('Tăng %% nguyền rủa', '增加%%诅咒')
add_map('Tăng sức tấn công Pet lên %%', '增加宠物攻击力%%')
add_map('(Bạn cần thêm %d cấp độ nữa)', '(还需要%d级)')
add_map('(Bạn cần thêm %d điểm nữa)', '(还需要%d点)')

# === Harmony options ===
add_map('ng lực tấn công thấp nhất', '最低攻击力')
add_map('ng lực tấn công cao nhất', '最高攻击力')
add_map('Giảm yêu cầu sức mạnh', '减少力量需求')
add_map('Giảm yêu cầu nhanh nhẹn', '减少敏捷需求')
add_map('ng lực tấn công (thấp nhất/cao nhất)', '攻击力(最低/最高)')
add_map('Tăng độ bền', '增加耐久度')
add_map('Tăng sức phòng thủ', '增加防御力')
add_map('Giảm yêu cầu thể lực', '减少体力需求')
add_map('Giảm yêu cầu năng lượng', '减少能量需求')

# === Socket options ===
add_map('ng sức tấn công/ma lực', '攻击力/魔法力')
add_map('ng sức phòng thủ của SD', 'SD防御力')
add_map('ng sức tấn công tuyệt chiêu', '技能攻击力')
add_map('t chiêu', '技能的')

# === Skill tooltips ===
add_map('hao mòn của vũ khí và giáp', '武器和盔甲的磨损')
add_map('ang sử dụng giảm', '使用中减少')
add_map('Không bao gồm các item CashShop', '不包括商城物品')
add_map('m yêu cầu', '需求')
add_map('i phục mana', '恢复魔力')
add_map('i phục HP', '恢复生命值')
add_map('cấp bậc', '等级阶位')
add_map('Cấp kỹ năng', '技能等级')
add_map('sấm sét', '雷霆')
add_map('Chém xoáy lên', '上斩')
add_map('c xoáy', '旋转')
add_map('Lượng nước', '水量')
add_map('Lửa Địa Ngục', '地狱火')
add_map('Phòng thủ', '防御')

# === Quest ===
add_map("Find the 'Scroll of Emperor'!", "找到'帝王卷轴'！")
add_map('Three Treasures of Mu', 'Mu的三大宝藏')
add_map("Gain 'Hero status'!", "获得'英雄状态'！")
add_map("Secret of 'Dark Stone'", "'暗黑之石'的秘密")
add_map('Evidence of Strength', '力量的证据')
add_map('Proof of Strength', '力量的证明')

# === Quest Words (tutorial text) ===
add_map('Welcome to the world of Mu.', '欢迎来到Mu的世界。')
add_map('We have been waiting for a hero like you to arrive and put a stop to the chaos brought on to the Mu realm by Kundun.', '我们一直在等待像你这样的英雄到来，阻止昆顿给Mu世界带来的混乱。')
add_map('However, journeys such as this are bound to be perilous.', '然而，这样的旅程充满危险。')
add_map('If you wish, we can provide you with a simple tutorial. What do you say?', '如果你愿意，我们可以提供一个简单的教程。你觉得如何？')
add_map('Cancel', '取消')
add_map('Accept', '接受')
add_map('Quest Completed', '任务完成')

# === Dialog ===
add_map('Aye! Is there anything you need?', '是的！您需要什么？')
add_map('Hello warrior. How can I help you?', '你好勇士。需要帮忙吗？')
add_map('What brings you here?', '什么风把你吹来了？')
add_map('Good day. Would you like to trade?', '日安，想交易吗？')

# === Items already in Item.txt ===
add_map('Chùy Thủ', '匕首')
add_map('Đoản Đao', '短刀')
add_map('Trường Kiếm', '长剑')
add_map('Kiếm Nhật', '日本刀')
add_map('Đao Sát Thủ', '杀手刀')
add_map('Khoái Đao', '快刀')
add_map('Kiếm La Mã', '罗马剑')
add_map('Mã Tấu', '砍刀')
add_map('Xà Đao', '蛇刀')
add_map('Kiếm Rồng Lửa', '火龙剑')
add_map('Kiếm Ánh Sáng', '光之剑')
add_map('Kiếm Ma Thuật', '魔法剑')
add_map('Thái Dương Kiếm', '太阳剑')
add_map('Hỏa Đao', '火刀')
add_map('Kiếm Điện', '雷电剑')
add_map('Thiết Kiếm', '铁剑')
add_map('Kiếm Hủy Diệt', '毁灭之剑')
add_map('Thiên Ma Kiếm', '天魔剑')
add_map('Lôi Phong Đao', '雷风刀')
add_map('Thiên Tử Kiếm', '天子剑')
add_map('Cuồng Phong Đao', '狂风刀')
add_map('Đao Sinh Mệnh', '生命之刀')
add_map('Đao Quyền Năng', '权能之刀')
add_map('Đao Hồng Long', '红龙刀')
add_map('Ỷ Thiên Đao', '倚天刀')
add_map('Hỏa Tinh Kiếm', '火星剑')
add_map('Hỏa Long Kiếm', '火龙剑')
add_map('Bích Ngọc Kiếm', '碧玉剑')
add_map('Bá Vương Kiếm', '霸王剑')
add_map('Linh Phong Kiếm', '灵风剑')
add_map('Hỏa Kiếm', '火焰剑')
add_map('Ảo Ảnh Đao', '幻影刀')
add_map('Nắm đấm Địa Long', '地龙之拳')
add_map('Nắm đấm Bạch Hổ', '白虎之拳')
add_map('Nắm đấm Quyền Lực', '权力之拳')
add_map('Vuốt Phượng Hoàng', '凤凰爪')
add_map('Tình Kiếm', '情剑')
add_map('Kiếm Huyết Thần', '血神剑')
add_map('Kiếm Huyết Thần (Phép)', '血神剑(魔)')
add_map('Kiếm Ma Thuật Bạc (Phép', '白银魔法剑(魔)')
add_map('Kiếm Hắc Thần', '黑神剑')
add_map('Kiếm Hắc Thần (Phép)', '黑魔神剑(魔)')
add_map('Kiếm Thánh Thần', '圣神剑')
add_map('Kiếm Thánh Thần (Phép)', '圣神剑(魔)')
add_map('Huyết Thần Kiếm', '血神剑')
add_map('Hắc Thần Kiếm', '黑神剑')
add_map('Thánh Thần Kiếm', '圣神剑')
add_map('Huyết Thần Chùy', '血神锤')
add_map('Hắc Thần Chùy', '黑神锤')
add_map('Thánh Thần Chùy', '圣神锤')
add_map('Huyết Thần Đao', '血神刀')
add_map('Hắc Thần Đao', '黑神刀')
add_map('Thánh Thần Đao', '圣神刀')
add_map('Kiếm Thiên Tử', '天子剑')
add_map('KiếmThiên Tử', '天子剑')
add_map('Gậy Thiên Nữ', '天女杖')
add_map('Sách Phóng Độc', '毒咒术')
add_map('Sách Thiên Thạch', '陨石术')
add_map('Sách Phóng Sét', '雷电术')
add_map('Sách Quả Cầu Lửa', '火球术')
add_map('Sách Cột Lửa', '火柱术')
add_map('Sách Đóng Băng', '冰冻术')
add_map('Sách Lốc Xoáy', '龙卷风')
add_map('Sách Lửa Địa Ngục', '地狱火')
add_map('Sách Sóng Âm', '音波术')
add_map('Sách Luồng Nước Xanh', '水龙术')
add_map('Sách Mưa Sao Băng', '流星雨')
add_map('Sách Vòng Tròn Lửa', '火龙环')
add_map('Vòng Tròn Năng Lượng', '能量环')
add_map('Sách Mưa Độc Tố', '毒雨术')
add_map('Sách Mưa Băng Tuyết', '冰雪雨')
add_map('Sách Nova', '新星术')
add_map('Sách Lôi Điện', '闪电术')
add_map('Sách Hút Máu', '吸血术')
add_map('Sách Shock Điện', '电击术')
add_map('Sách Phản Hồi', '反射术')
add_map('Sách Hộ Công', '护体神功')
add_map('Sách Ru Ngủ', '催眠术')
add_map('Sách Giảm Sức Đánh', '削弱术')
add_map('Sách Giảm Phòng Thủ', '破防术')
add_map('Sách Vòng Tròn Ma Thuật', '魔法环')
add_map('Sách Bão Ánh Sáng', '光之暴风')
add_map('Sách Vật Ngã', '跌倒术')
add_map('Sách Ảo Ảnh Liên Hoàn', '幻影连击')
add_map('Sách Gầm Thét', '咆哮术')
add_map('Sách Hơi Thở Rồng', '龙息术')
add_map('Sách Xuyên Thấu', '穿透术')
add_map('Sách Tăng Thể Lực', '体力增强')
add_map('Sách Hộ Thân', '护身术')

# === Dialog NPC text ===
add_map('Aye! Is there anything you need?', '是的！您需要什么？')

# === ItemLevelTooltip ===
add_map('n sách ế Vương', '帝王之书')
add_map('Chiếc Nhẫn Vinh Quang', '荣光之戒')
add_map('Thanh Gươm Gãy', '断剑')
add_map('Viên Ngọc Cổ', '古老宝石')
add_map('Hộp may mắn', '幸运盒子')
add_map('Trái tim tình yêu', '爱心')
add_map('Phao Hoa', '烟花')
add_map('Huy Chuong Bac', '银质勋章')
add_map('Huy Chuong Vang', '金质勋章')
add_map('p Kundun +1', '昆顿 +1')
add_map('Star of the Sacred Birth', '圣星之诞')
add_map('Sói Hoàng Kim', '黄金狼')

# === Misc VN phrases ===
add_map('Chú ý!', '注意！')
add_map('Chú ý có lỗi', '注意有错误')
add_map('vui lòng thoát ra khỏi game', '请退出游戏')
add_map('Kết nối với máy chủ đã bị ngắt', '与服务器的连接已断开')
add_map('cập nhật Driver mới nhất cho card màn hình', '请更新最新的显卡驱动')
add_map('Lỗi', '错误')
add_map('Chương trình bị nhiễm virus', '程序被病毒感染')
add_map('Chương trình chống hack bị ngắt đoạn', '反外挂程序被中断')
add_map('vui lòng kết nối lại', '请重新连接')
add_map('Lỗi tập tin', '文件错误')
add_map('vui lòng liên hệ admin để được hỗ trợ', '请联系管理员')
add_map('vui lòng nhấp chuột vào nút kết thúc', '请点击结束按钮')
add_map('Vui lòng kiểm tra tập tin', '请检查文件')
add_map('Lỗi dữ liệu', '数据错误')
add_map('Thiếu tập tin', '缺少文件')
add_map('tải về lại ở trang chủ', '请从官网重新下载')
add_map('Cập nhật trò chơi bị lỗi', '游戏更新失败')
add_map('bạn hãy cập nhật lại', '请重新更新')
add_map('Khởi động lại máy để hoàn thành Cập nhật', '重启计算机以完成更新')
add_map('Kết nối với máy chủ cập nhật không thành công', '连接更新服务器失败')
add_map('gỡ bỏ và cài đặt lại MU', '卸载并重新安装MU')
add_map('Phát hiện chương trình Hack', '检测到外挂程序')
add_map('Không thể lưu thông tin vào Registry', '无法保存信息到注册表')
add_map('Cập nhật', '更新')
add_map('Kết nối', '连接')
add_map('đăng nhập', '登录')
add_map('đăng ký', '注册')
add_map('mật khẩu', '密码')
add_map('tài khoản', '账号')
add_map('máy chủ', '服务器')
add_map('cửa hàng', '商店')
add_map('thông tin', '信息')
add_map('cài đặt', '设置')
add_map('ngôn ngữ', '语言')
add_map('tên nhân vật', '角色名')
add_map('bạn bè', '好友')
add_map('công hội', '战盟')
add_map('menu chính', '主菜单')
add_map('đồng ý', '确认')
add_map('hủy bỏ', '取消')
add_map('Đóng', '关闭')
add_map('Lưu', '保存')
add_map('Xóa', '删除')
add_map('Thoát', '退出')
add_map('Quay lại', '返回')
add_map('Tiếp theo', '下一步')
add_map('Hoàn thành', '完成')
add_map('Năng Cấp Cánh VIP', 'VIP翅膀升级')
add_map('Năng Cấp Cánh VIP 2', 'VIP翅膀升级2')
add_map('Năng Cấp Cánh VIP 3', 'VIP翅膀升级3')
add_map('Năng Cấp Cánh VIP 4', 'VIP翅膀升级4')
add_map('Năng Cấp Cánh VIP 5', 'VIP翅膀升级5')
add_map('Năng Cấp Cánh VIP 6', 'VIP翅膀升级6')
add_map('Năng Cấp Cánh VIP 7', 'VIP翅膀升级7')
add_map('Năng Cấp Cánh VIP 8', 'VIP翅膀升级8')
add_map('Năng Cấp Cánh VIP 9', 'VIP翅膀升级9')

# === Common VN words (context-independent) ===
add_map('Bạn', '你')
add_map('bạn', '你')
add_map('không', '不')
add_map('có', '有')
add_map('các', '各')
add_map('những', '那些')
add_map('một', '一')
add_map('và', '和')
add_map('để', '为了')
add_map('cho', '给')
add_map('với', '与')
add_map('từ', '从')
add_map('đến', '到')
add_map('qua', '通过')
add_map('sau', '后')
add_map('trước', '前')
add_map('khi', '当')
add_map('nếu', '如果')
add_map('thì', '则')
add_map('này', '这')
add_map('đó', '那')
add_map('ở', '在')
add_map('tại', '在')
add_map('lên', '上')
add_map('xuống', '下')
add_map('ra', '出')
add_map('vào', '入')
add_map('về', '回')
add_map('đã', '已')
add_map('sẽ', '将')
add_map('đang', '正在')
add_map('cần', '需要')
add_map('phải', '必须')
add_map('thể', '能')
add_map('được', '被')
add_map('bị', '被')
add_map('còn', '还')
add_map('rất', '很')
add_map('nên', '应')
add_map('mới', '才')
add_map('cùng', '同')
add_map('đều', '都')
add_map('chỉ', '只')
add_map('đúng', '正确')
add_map('sai', '错误')
add_map('tốt', '好')
add_map('xấu', '坏')
add_map('mở', '开')
add_map('đóng', '关')
add_map('xem', '看')
add_map('làm', '做')
add_map('nói', '说')
add_map('chọn', '选')
add_map('dùng', '用')
add_map('sử dụng', '使用')
add_map('cách', '方式')
add_map('theo', '按')
add_map('trong', '在')
add_map('ngoài', '外')
add_map('trên', '上')
add_map('dưới', '下')
add_map('giữa', '中间')
add_map('người', '人')
add_map('tên', '名')
add_map('số', '数')
add_map('tiền', '钱')
add_map('giá', '价')
add_map('loại', '类')
add_map('món', '件')
add_map('cái', '个')
add_map('nơi', '处')
add_map('nơi', '地方')
add_map('nữa', '再')
add_map('thêm', '添加')
add_map('thiếu', '缺少')
add_map('đủ', '足够')
add_map('nhập', '输入')
add_map('gõ', '输入')
add_map('ấn', '按')
add_map('bấm', '按')
add_map('nhấn', '按')
add_map('nhấp', '点击')
add_map('chuyển', '转换')
add_map('đổi', '换')
add_map('gửi', '发送')
add_map('nhận', '接收')
add_map('mất', '失去')
add_map('có', '有')
add_map('tìm', '找')
add_map('thấy', '见')
add_map('gặp', '遇到')
add_map('gọi', '叫')
add_map('đặt', '设置')
add_map('trả', '还')
add_map('lấy', '取')
add_map('đem', '带')
add_map('mang', '带')
add_map('giữ', '保持')
add_map('bỏ', '放')

# === Common VN phrases ===
add_map('vui lòng', '请')
add_map('liên hệ', '联系')
add_map('hỗ trợ', '支持')
add_map('diệt Virus', '杀毒')
add_map('cập nhật', '更新')
add_map('tập tin', '文件')
add_map('thư mục', '目录')
add_map('trang chủ', '官网')
add_map('kết nối', '连接')
add_map('thoát ra', '退出')
add_map('đăng nhập', '登录')
add_map('đăng ký', '注册')
add_map('mật khẩu', '密码')
add_map('tài khoản', '账号')
add_map('máy chủ', '服务器')
add_map('nhân vật', '角色')
add_map('vật phẩm', '物品')
add_map('cửa hàng', '商店')
add_map('giao dịch', '交易')
add_map('thông tin', '信息')
add_map('cài đặt', '设置')
add_map('ngôn ngữ', '语言')
add_map('bạn bè', '好友')
add_map('đồng ý', '同意')
add_map('hủy bỏ', '取消')
add_map('quay lại', '返回')
add_map('tiếp theo', '下一步')
add_map('hoàn thành', '完成')
add_map('bắt đầu', '开始')
add_map('kết thúc', '结束')
add_map('tiếp tục', '继续')
add_map('tạm dừng', '暂停')
add_map('khôi phục', '恢复')
add_map('sửa chữa', '修理')
add_map('mua bán', '买卖')
add_map('điểm kinh nghiệm', '经验值')
add_map('sức đánh', '攻击力')
add_map('phòng thủ', '防御力')
add_map('chống đỡ', '抵挡')
add_map('phòng vệ', '防御')
add_map('sức chống phép', '魔法防御')
add_map('khả năng', '能力')
add_map('kỹ năng', '技能')
add_map('năng lượng', '能量')
add_map('sinh lực', '生命值')
add_map('thể lực', '体力')
add_map('sức mạnh', '力量')
add_map('nhanh nhẹn', '敏捷')
add_map('thông thường', '普通')
add_map('cao cấp', '高级')
add_map('cấp độ', '等级')
add_map('thời gian', '时间')
add_map('khoảng cách', '距离')
add_map('phạm vi', '范围')
add_map('tỉ lệ', '比例')
add_map('thành công', '成功')
add_map('thất bại', '失败')
add_map('chiến đấu', '战斗')
add_map('chiến thắng', '胜利')
add_map('tử vong', '死亡')
add_map('hồi sinh', '复活')
add_map('di chuyển', '移动')
add_map('dịch chuyển', '传送')
add_map('tấn công', '攻击')
add_map('phòng thủ', '防御')
add_map('né tránh', '闪避')
add_map('chính xác', '命中')
add_map('bạo kích', '暴击')
add_map('sát thương', '伤害')
add_map('xác suất', '概率')
add_map('tăng', '增加')
add_map('giảm', '减少')
add_map('tối đa', '最大')
add_map('tối thiểu', '最小')
add_map('thấp nhất', '最低')
add_map('cao nhất', '最高')
add_map('sự kiện', '活动')
add_map('nhiệm vụ', '任务')
add_map('phần thưởng', '奖励')
add_map('quà tặng', '礼物')
add_map('vĩnh viễn', '永久')
add_map('tạm thời', '临时')

# === Game UI phrases ===
add_map('Sức mạnh cú chém', '斩击力量')
add_map('Có thể kết hợp tạo ra Combo', '可以组合连击')
add_map('Rượu tình', '爱情酒')
add_map('Huy chương Bạc', '银质勋章')
add_map('Huy chương Vàng', '金质勋章')
add_map('Ngôi sao may mắn', '幸运星')
add_map('Nhẫn biến hình', '变形戒指')
add_map('Nếu ném ra đất sẽ có phần thưởng', '扔到地上会有奖励')
add_map('Chỉ rớt một loại vật phẩm', '只掉落一种物品')
add_map('Trái tim Chúa tể', '领主之心')
add_map('Bánh Trung Thu', '月饼')
add_map('Tìm gặp NPC Trao đổi', '找NPC交换')
add_map('Cách sử dụng các phím Nút chức năng', '功能键使用方法')
add_map('F1: Giúp đỡ: Tắt/Mở', 'F1: 帮助: 开/关')
add_map('Q: Sử dụng bình tăng Máu', 'Q: 使用生命药水')
add_map('W: Sử dụng bình tăng Năng lượng', 'W: 使用能量药水')
add_map('E: Sử dụng bình thuốc giải độc', 'E: 使用解毒药水')
add_map('Shift: Cố định nhân vật', 'Shift: 固定角色')
add_map('Alt: Hiện tên vật dụng rơi trên mặt đất', 'Alt: 显示地面物品名')
add_map('PrintScreen: Chụp ảnh', 'PrintScreen: 截图')
add_map('Phím mũi tên lên', '上箭头键')
add_map('Xem lại đoạn nói chuyện', '查看聊天记录')
add_map('Tab: Chuyển vào cửa sổ Đăng nhập', 'Tab: 切换到登录窗口')
add_map('Đánh dấu ~ trước câu nói để nói chuyện với thành viên trong Nhóm', '在句子前加~与队员聊天')
add_map('Đánh dấu @ trước câu nói để nói chuyện với thành viên trong Hội', '在句子前加@与战盟成员聊天')
add_map('Đánh dấu # trước câu nói để câu nói hiện ra trong thời gian lâu hơn', '在句子前加#延长显示时间')
add_map('Cách sử dụng chế độ trò chuyện riêng', '私聊模式使用方法')
add_map('Chỉ chuột vào Chủ Hội sau đó đánh /guild', '指向战盟盟主然后输入/guild')
add_map('để xin vào Hội', '申请加入战盟')
add_map('Sau %d giây nữa, bạn sẽ di chuyển đến vùng đất khác', '%d秒后，你将传送到其他区域')
add_map('Bạn muốn trở thành chủ Hội không?', '你想成为战盟盟主吗？')
add_map('Nếu bạn muốn gia nhập Hội', '如果你想加入战盟')
add_map('Chỉ chuột vào chủ Hội rồi đánh /guild', '指向盟主后输入/guild')
add_map('Chỉ chuột vào người muốn mời vào', '指向要邀请的人')
add_map('Sau đó gõ /party', '然后输入/party')
add_map('Nếu đối phương chấp nhận thì Nhóm sẽ được tạo', '如果对方同意则组队成功')
add_map('Nếu thành lập Nhóm thì điểm kinh nghiệm', '如果建立队伍，经验值')
add_map('sau khi giết quái vật sẽ được chia ra', '杀死怪物后将会分配')
add_map('Tùy theo cấp độ của từng nhân vật', '根据每个角色的等级')
add_map('điểm kinh nghiệm nhận được sẽ khác nhau', '获得的经验值将会不同')
add_map('Bạn đã gia nhập Hội này', '你已加入此战盟')
add_map('Bạn đã vào nhóm này', '你已加入此队伍')
add_map('Phải rời khỏi Nhóm mới có thể bước vào Atlans', '必须离开队伍才能进入亚特兰斯')
add_map('Bạn không thể sử dụng Kỳ Lân khi ở Atlans', '在亚特兰斯不能使用麒麟')
add_map('Bạn phải sử dụng Cánh, Áo choàng hoặc Quái Điểu mới có thể đến Icarus', '必须使用翅膀或披风才能去伊卡洛斯')
add_map('Không thể quăng món đồ này', '无法丢弃此物品')
add_map('Mũi tên điều khiển to dần khi di chuyển về phía dưới', '控制箭头向下移动时逐渐变大')
add_map('Bạn chưa tham gia vào Hội', '你尚未加入战盟')
add_map('Giải tán', '解散')
add_map('Thông tin Nhóm', '队伍信息')
add_map('Điểm dư', '剩余点数')
add_map('Lượng Sinh lực', '生命值')
add_map('Nội lực', '内力')
add_map('Sức đánh Ma pháp', '魔法攻击力')
add_map('Bạn không thể sử dụng', '你不能使用')
add_map('món này', '此物品')
add_map('Dùng cho', '适用于')
add_map('Giá mua', '购买价格')
add_map('Giá bán', '出售价格')
add_map('Tốc độ', '速度')
add_map('Sức chống đỡ', '抵挡力')
add_map('Sức chống phép', '魔法抗性')
add_map('Khả năng phòng vệ', '防御能力')
add_map('Tự động phục hồi', '自动恢复')
add_map('Khả năng sử dụng khi chuyển động', '移动时可用')
add_map('Khả năng đánh Ma pháp', '魔法攻击能力')
add_map('Chú thích', '注释')
add_map('Zen có thể chuyển hóa thành Rena', '金币可以转换为Rena')
add_map('Tắt/Mở cửa sổ Hội', '开/关战盟窗口')
add_map('Tắt/Mở cửa sổ Nhóm', '开/关队伍窗口')
add_map('Tắt/Mở cửa sổ nhân vật', '开/关角色窗口')
add_map('Tắt/Mở thùng đồ', '开/关背包')
add_map('Sửa chữa', '修理')
add_map('Sửa toàn bộ', '全部修理')
add_map('Phí sửa chữa', '修理费')
add_map('Kho đồ', '仓库')
add_map('Gửi tiền', '存钱')
add_map('Đang khóa', '已锁定')
add_map('Ấn nút chọn con số may mắn', '按按钮选择幸运数字')
add_map('Nhấn nút Đăng ký tên', '按注册名称按钮')
add_map('Lũy tích', '累积')
add_map('Thay đổi ống cung tên', '更换箭筒')
add_map('Đã hết cung tên', '箭已用完')
add_map('Bạn phải đóng thùng đồ, sau đó mới có thể dịch chuyển', '你必须关闭背包才能传送')
add_map('Cấp độ của bạn phải đủ %d mới có thể dịch chuyển', '你的等级必须达到%d才能传送')
add_map('Phí giữ đồ', '保管费')
add_map('Bắt đầu nhắn tin nhắn riêng', '开始发送私信')
add_map('Không nhận tin nhắn riêng', '不接受私信')
add_map('Yêu cầu cấp độ %d trở lên', '需要等级%d以上')
add_map('Còn: %d (%d) Tên Cung', '剩余: %d (%d) 弓名')
add_map('Còn: %d (%d) Tên Nỏ', '剩余: %d (%d) 弩名')
add_map('Hãy kiểm tra kỹ và chắc chắn đúng loại', '请仔细检查确认类型正确')
add_map('hàng hóa trước khi giao dịch', '交易前请确认商品')
add_map('Cấm địa Hoàng gia', '皇家禁地')
add_map('Quảng Trường Quỷ', '恶魔广场')
add_map('Hỗn Nguyên Lâu', '混沌城堡')
add_map('Đặt trước: công việc', '预设: 职业')
add_map('Sức phòng vệ', '防御力')

# === slide text ===
add_map('SOLAR ??P TRAI V? ??I', '太阳之心')
add_map('SOLAR SYSTEM TRAI TIM', '太阳系之心')

# === Custom items ===
add_map('Vuốt Thiên Tử (Cấp 1)', '天子爪 (1级)')
add_map('Vuốt Thiên Tử (Cấp 2)', '天子爪 (2级)')
add_map('Vuốt Thiên Tử (Cấp 3)', '天子爪 (3级)')
add_map('Chuỳ Vương (RF)', '王锤 (RF)')
add_map('Trượng Thiên Tử (Cấp 3', '天子杖 (3级)')
add_map('Thương Hắc Thần', '黑神矛')
add_map('Thương Thánh Thần', '圣神矛')
add_map('Gậy Thiên Nữ (Cấp 2)', '天女杖 (2级)')
add_map('Gậy Thiên Nữ (Cấp 3)', '天女杖 (3级)')
add_map('Chuỳ Vương (DW-SUM-MG)', '王锤 (DW-SUM-MG)')
add_map('Khiên Huyết Thần', '血神盾')
add_map('Khiên Hắc Thần', '黑神盾')
add_map('Khiên Thánh Thần', '圣神盾')
add_map('Nhẫn Tử Thần', '死神戒指')
add_map('Nhẫn Thiên Sứ', '天使戒指')
add_map('Nhẫn Bóng Đêm', '暗夜戒指')
add_map('Dây Chuyền Tử Thần', '死神项链')
add_map('Dây Chuyền Thiên Sứ', '天使项链')
add_map('Mũ Hiệp Sĩ Thường DK', '普通骑士头盔 DK')
add_map('Mũ Hiệp Sĩ Thường DW', '普通骑士头盔 DW')
add_map('Mũ Hiệp Sĩ Thường ELF', '普通骑士头盔 ELF')
add_map('Mũ Hiệp Sĩ Thường SUM', '普通骑士头盔 SUM')
add_map('Mũ Hiệp Sĩ Thường MG', '普通骑士头盔 MG')
add_map('Mũ Hiệp Sĩ Thường DL', '普通骑士头盔 DL')
add_map('Mũ Hiệp Sĩ Thường RF', '普通骑士头盔 RF')
add_map('Mũ Hiệp Sĩ VIP DK', 'VIP骑士头盔 DK')
add_map('Mũ Hiệp Sĩ VIP DW', 'VIP骑士头盔 DW')
add_map('Mũ Hiệp Sĩ VIP ELF', 'VIP骑士头盔 ELF')
add_map('Mũ Hiệp Sĩ VIP SUM', 'VIP骑士头盔 SUM')
add_map('Mũ Hiệp Sĩ VIP MG', 'VIP骑士头盔 MG')
add_map('Mũ Hiệp Sĩ VIP DL', 'VIP骑士头盔 DL')
add_map('Mũ Hiệp Sĩ VIP RF', 'VIP骑士头盔 RF')
add_map('Áo Hiệp Sĩ Thường DK', '普通骑士铠甲 DK')
add_map('Áo Hiệp Sĩ Thường DW', '普通骑士铠甲 DW')
add_map('Áo Hiệp Sĩ Thường Elf', '普通骑士铠甲 ELF')
add_map('Áo Hiệp Sĩ Thường SUM', '普通骑士铠甲 SUM')
add_map('Áo Hiệp Sĩ Thường MG', '普通骑士铠甲 MG')
add_map('Áo Hiệp Sĩ Thường DL', '普通骑士铠甲 DL')
add_map('Áo Hiệp Sĩ Thường RF', '普通骑士铠甲 RF')
add_map('Áo Hiệp Sĩ VIP DK', 'VIP骑士铠甲 DK')
add_map('Áo Hiệp Sĩ VIP DW', 'VIP骑士铠甲 DW')
add_map('Áo Hiệp Sĩ VIP Elf', 'VIP骑士铠甲 ELF')
add_map('Áo Hiệp Sĩ VIP SUM', 'VIP骑士铠甲 SUM')
add_map('Áo Hiệp Sĩ VIP MG', 'VIP骑士铠甲 MG')
add_map('Áo Hiệp Sĩ VIP DL', 'VIP骑士铠甲 DL')
add_map('Áo Hiệp Sĩ VIP RF', 'VIP骑士铠甲 RF')
add_map('Quần Hiệp Sĩ Thường DK', '普通骑士护腿 DK')
add_map('Quần Hiệp Sĩ Thường DW', '普通骑士护腿 DW')
add_map('Quần Hiệp Sĩ Thường El', '普通骑士护腿 ELF')
add_map('Quần Hiệp Sĩ Thường SU', '普通骑士护腿 SUM')
add_map('Quần Hiệp Sĩ Thường MG', '普通骑士护腿 MG')
add_map('Quần Hiệp Sĩ Thường DL', '普通骑士护腿 DL')
add_map('Quần Hiệp Sĩ Thường RF', '普通骑士护腿 RF')
add_map('Quần Hiệp Sĩ VIP DK', 'VIP骑士护腿 DK')
add_map('Quần Hiệp Sĩ VIP DW', 'VIP骑士护腿 DW')
add_map('Quần Hiệp Sĩ VIP Elf', 'VIP骑士护腿 ELF')
add_map('Quần Hiệp Sĩ VIP SUM', 'VIP骑士护腿 SUM')
add_map('Quần Hiệp Sĩ VIP MG', 'VIP骑士护腿 MG')
add_map('Quần Hiệp Sĩ VIP DL', 'VIP骑士护腿 DL')
add_map('Quần Hiệp Sĩ VIP RF', 'VIP骑士护腿 RF')
add_map('Găng Hiệp Sĩ Thường DK', '普通骑士手套 DK')
add_map('Găng Hiệp Sĩ Thường DW', '普通骑士手套 DW')
add_map('Găng Hiệp Sĩ Thường ELF', '普通骑士手套 ELF')
add_map('Găng Hiệp Sĩ Thường SUM', '普通骑士手套 SUM')
add_map('Găng Hiệp Sĩ Thường MG', '普通骑士手套 MG')
add_map('Găng Hiệp Sĩ Thường DL', '普通骑士手套 DL')
add_map('Găng Hiệp Sĩ Thường RF', '普通骑士手套 RF')
add_map('Găng Hiệp Sĩ VIP DK', 'VIP骑士手套 DK')
add_map('Găng Hiệp Sĩ VIP DW', 'VIP骑士手套 DW')
add_map('Găng Hiệp Sĩ VIP ELF', 'VIP骑士手套 ELF')
add_map('Găng Hiệp Sĩ VIP SUM', 'VIP骑士手套 SUM')
add_map('Găng Hiệp Sĩ VIP MG', 'VIP骑士手套 MG')
add_map('Găng Hiệp Sĩ VIP DL', 'VIP骑士手套 DL')
add_map('Găng Hiệp Sĩ VIP RF', 'VIP骑士手套 RF')
add_map('Giầy Hiệp Sĩ Thường DK', '普通骑士靴子 DK')
add_map('Giầy Hiệp Sĩ Thường DW', '普通骑士靴子 DW')
add_map('Giầy Hiệp Sĩ Thường El', '普通骑士靴子 ELF')
add_map('Giầy Hiệp Sĩ Thường SU', '普通骑士靴子 SUM')
add_map('Giầy Hiệp Sĩ Thường MG', '普通骑士靴子 MG')
add_map('Giầy Hiệp Sĩ Thường DL', '普通骑士靴子 DL')
add_map('Giầy Hiệp Sĩ Thường RF', '普通骑士靴子 RF')
add_map('Giầy Hiệp Sĩ VIP DK', 'VIP骑士靴子 DK')
add_map('Giầy Hiệp Sĩ VIP DW', 'VIP骑士靴子 DW')
add_map('Giầy Hiệp Sĩ VIP Elf', 'VIP骑士靴子 ELF')
add_map('Giầy Hiệp Sĩ VIP SUM', 'VIP骑士靴子 SUM')
add_map('Giầy Hiệp Sĩ VIP MG', 'VIP骑士靴子 MG')
add_map('Giầy Hiệp Sĩ VIP DL', 'VIP骑士靴子 DL')
add_map('Giầy Hiệp Sĩ VIP RF', 'VIP骑士靴子 RF')
add_map('Xiên hạt băng', '冰属性串')
add_map('Xiên hạt gió', '风属性串')
add_map('Xiên hạt sét', '雷属性串')
add_map('Xiên hạt đất', '地属性串')
add_map('Xiên hạt lửa', '火属性串')
add_map('Xiên hạt nước', '水属性串')
add_map('Áo Choàng Của Vua nhỏ', '小国王披风')
add_map('Cánh Vũ Linh nhỏ', '小精灵翼')
add_map('Cánh Tiên Nữ nhỏ', '小仙女翼')
add_map('Cánh Thiên Đàng nhỏ', '小天堂翼')
add_map('Cánh Quỷ nhỏ', '小鬼翼')
add_map('Áo Choàng Chiến Binh nhỏ', '小战士披风')
add_map('Áo Choàng Tử Thần(2.5)', '死神披风 (2.5)')
add_map('Cánh Hỗn Nguyên(2.5)', '混沌翼 (2.5)')
add_map('Cánh Ma Thuật(2.5)', '魔法翼 (2.5)')
add_map('Cánh Hỏa Thần(2.5)', '火神翼 (2.5)')
add_map('Cánh Ác Quỷ', '恶魔翼')
add_map('Cánh Thiên Thần', '天使翼')
add_map('Cụm Ngọc Sinh Mệnh', '生命宝石簇')
add_map('Cụm Ngọc Sáng Tạo', '创造宝石簇')
add_map('Cụm Đá Hộ Mệnh', '守护石簇')
add_map('Cụm Đá Nguyên Thủy', '原始石簇')
add_map('Cụm Đá Tạo Hóa', '造化石簇')
add_map('Cụm Ngọc Hỗn Nguyên', '混沌宝石簇')
add_map('Cụm Đá Tinh Luyện Thấp', '低级精炼石簇')
add_map('Cụm Đá Tinh Luyện Cao', '高级精炼石簇')
add_map('Phượng Hoàng Lửa', '火凤凰')
add_map('Chúa Tể Kundun', '昆顿领主')
add_map('Quỷ Bóng Đêm VIP', '暗夜鬼 VIP')
add_map('Nhện Độc', '毒蜘蛛')
add_map('Chúa Tể Bóng Đêm', '暗夜领主')
add_map('Xương Thần Chết', '死神骨头')
add_map('Da Quỷ Vương', '魔王皮')
add_map('Lông Vũ Phượng Hoàng', '凤凰羽毛')
add_map('Linh Hồn Dơi Lửa', '火蝙蝠灵魂')
add_map('Đá Thần Vĩ Đại', '伟大神石')
add_map('Ngọn Lửa Garuda', '迦楼罗之火')
add_map('Lông Vịt Garuda', '迦楼罗之羽')
add_map('Đá Thần Cổ Xưa', '上古神石')
add_map('Thép Thiên Đường', '天堂之钢')
add_map('Búa Archangels', '大天使之锤')
add_map('Nguyên Liệu Ép VKR Cấp 3', '合成武器材料 3级')
add_map('Nguyên Liệu Set Hiệp Sĩ', '骑士套装材料')
add_map('Sách thuộc tính', '属性书')
add_map('Sách thuộc tính 1', '属性书 1')
add_map('Sách thuộc tính 2', '属性书 2')
add_map('Sách thuộc tính 3', '属性书 3')
add_map('Sách thuộc tính 4', '属性书 4')
add_map('Sách thuộc tính 5', '属性书 5')
add_map('Sách thuộc tính 6', '属性书 6')
add_map('Dây chuyền trái tim', '心形项链')
add_map('Nhẫn trái tim', '心形戒指')
add_map('TÔM', '虾')
add_map('CÁ', '鱼')
add_map('HƯƠU', '鹿')
add_map('GÀ', '鸡')
add_map('SẤP ĐÔI', '双倍')
add_map('Sói', '狼')
add_map('Ngựa', '马')
add_map('Chiến Mã', '战马')
add_map('Thần Mã', '神马')
add_map('Thần Sói', '神狼')
add_map('Sói Ma', '魔狼')
add_map('Ngựa Ma', '魔马')
add_map('Lông Vũ', '羽毛')
add_map('Nanh Máu', '血牙')
add_map('Sừng', '角')
add_map('Cụm Đá', '石簇')
add_map('Cụm Ngọc', '宝石簇')
add_map('Pha Lê Đỏ', '红水晶')
add_map('Pha Lê Xanh', '蓝水晶')
add_map('Pha Lê Đen', '黑水晶')
add_map('Mảnh Sừng', '角碎片')
add_map('Mảnh Vỡ', '碎片')
add_map('Bùa', '护符')
add_map('Vé', '门票')
add_map('Vé Dịch Chuyển', '传送票')
add_map('Vé Hỗn Nguyên Lầu', '混沌城堡门票')
add_map('Bình', '药水')
add_map('Bình Máu', '生命药水')
add_map('Bình Phép', '魔法药水')
add_map('Bình SD', 'SD药水')
add_map('Bình Thuốc', '药剂')
add_map('Rương', '宝箱')
add_map('Hộp', '盒子')
add_map('Hộp Kẹo', '糖果盒')
add_map('Hộp Ngọc', '宝石盒')
add_map('Hộp Quà', '礼盒')
add_map('Thẻ Bài', '卡片')
add_map('Thẻ Bài Chaos', '混沌卡片')
add_map('Thẻ Bài Vàng', '金卡片')
add_map('Khuôn', '模具')
add_map('Phao Hoa', '烟花')
add_map('Pháo Hoa Noel', '圣诞烟花')
add_map('Kẹo Cam', '橙糖')
add_map('Kẹo Xanh', '绿糖')
add_map('Châu báu', '珠宝')
add_map('Bất ngờ', '惊喜')
add_map('Mãnh Tướng', '猛将')
add_map('Danh Dự', '荣誉')
add_map('Chiến Binh Danh Dự', '荣誉战士')
add_map('Phù Thủy', '巫师')
add_map('Thần Tượng', '神像')
add_map('Thành Tích', '成就')
add_map('Lính Giáo', '枪兵')
add_map('Quyền Trượng', '权杖')
add_map('Gấu Trúc', '熊猫')
add_map('Huy Hiệu Hoàng Tộc', '皇室徽章')
add_map('Huy Hiệu Lửa', '火徽章')
add_map('Huy Hiệu Gió', '风徽章')
add_map('Linh Hồn Chiến Mã', '战马之魂')
add_map('Linh Hồn Qụa Tinh', '乌鸦之魂')
add_map('Linh hồn Sói Tinh', '狼精之魂')
add_map('Sói Tinh', '狼精')
add_map('Sói Tinh - Tấn Công', '狼精 - 攻击')
add_map('Sói Tinh - Phòng Thủ', '狼精 - 防御')
add_map('Sói Tinh - Hoàng Kim', '狼精 - 黄金')
add_map('Bạc', '银')
add_map('Vàng', '金')
add_map('Hoàng Kim', '黄金')
add_map('Đồng Xu', '金币')
add_map('Hồng Ngọc', '红宝石')
add_map('Ngọc Bích', '翡翠')
add_map('Thiên Sứ', '天使')
add_map('Nữ Thần Bảo Hộ', '守护女神')
add_map('Nữ Thần', '女神')
add_map('Huyết Thần', '血神')
add_map('Hắc Thần', '黑神')
add_map('Thánh Thần', '圣神')
add_map('Thức Tỉnh', '觉醒')
add_map('Mắt Xanh', '蓝眼')
add_map('Tim Bạc', '银心')
add_map('Nguyên Tố Băng', '冰元素')
add_map('Nguyên Tố Gió', '风元素')
add_map('Nguyên Tố Sét', '雷元素')
add_map('Nguyên Tố Đất', '地元素')
add_map('Nguyên Tố Lửa', '火元素')
add_map('Nguyên Tố Nước', '水元素')
add_map('Thuộc tính Nước', '水属性')
add_map('Thuộc tính Sét', '雷属性')
add_map('Trái tim Vàng', '金心')
add_map('Trái tim Chúa tể', '领主之心')
add_map('Trái tim', '心')
add_map('Quyển sách Đế Vương', '帝王之书')
add_map('Xương', '骨头')
add_map('Rìu', '斧')
add_map('Rìu Nhỏ', '小斧')
add_map('Rìu Thợ Săn', '猎斧')
add_map('Rìu Lưỡi Bạc', '银刃斧')
add_map('Rìu Hỏa Long', '火龙斧')
add_map('Chùy', '锤')
add_map('Chùy Vương', '王锤')
add_map('Trượng', '法杖')
add_map('Trượng Thép', '铁杖')
add_map('Trượng Đại Vương', '大王杖')
add_map('Trượng Tối Cao', '至高杖')
add_map('Trượng Băng Giá', '冰杖')
add_map('Trượng Thánh Thần', '圣神杖')
add_map('Trượng Tim Bạc', '银心杖')
add_map('Trượng Thức Tỉnh', '觉醒杖')
add_map('Trượng Mắt Xanh', '蓝眼杖')
add_map('Cung', '弓')
add_map('Cung Bạc', '银弓')
add_map('Cung Thiên Mệnh', '天命弓')
add_map('Cung Thiên Vũ', '天羽弓')
add_map('Cung Thánh Thần', '圣神弓')
add_map('Cung Tim Bạc', '银心弓')
add_map('Cung Thiên Sứ', '天使弓')
add_map('Nỏ Ánh Sáng', '光弩')
add_map('Gậy Tiên', '仙杖')
add_map('Gậy Lôi Phong', '雷风杖')
add_map('Gậy Thiên Sứ', '天使杖')
add_map('Gậy Thánh Thần', '圣神杖')
add_map('Gậy Tim Bạc', '银心杖')
add_map('Gậy Quỷ Vương', '魔王杖')
add_map('Gậy Hồng Ngọc', '红宝石杖')
add_map('Khuyển', '犬')
add_map('Khuyển Bão Điện', '电暴犬')
add_map('Khuyển Thánh Thần', '圣神犬')
add_map('Khuyển Tim Bạc', '银心犬')
add_map('Sách Quỷ Kiếm', '鬼剑书')
add_map('Sách Hắc Thần', '黑神书')
add_map('Sách Mắt Xanh', '蓝眼书')
add_map('Sách Sao Băng', '流星书')
add_map('Sách Tăng Ma Thuật', '魔法增强书')
add_map('Sách Tăng Ma Lực', '魔力增强书')
add_map('Bão Ánh Sáng', '光之暴风')
add_map('Khiên Diều', '鸢盾')
add_map('Khiên Kim Long', '金龙盾')
add_map('Khiên Trụ', '柱盾')
add_map('Khiên Xà', '蛇盾')
add_map('Khiên Ma Thuật', '魔法盾')
add_map('Khiên Vinh Quang', '荣光盾')
add_map('Khiên Bạch Dương', '白羊盾')
add_map('Khiên Mắt Xanh', '蓝眼盾')
add_map('Khiên Thức Tỉnh', '觉醒盾')
add_map('Khiên Tim Bạc', '银心盾')
add_map('Thương', '矛')
add_map('Lưỡi Hái', '镰刀')
add_map('Mũ Hỏa Long', '火龙盔')
add_map('Mũ Xương', '骨盔')
add_map('Mũ Nhân Sư', '狮身盔')
add_map('Mũ Trinh Nữ', '处女盔')
add_map('Mũ Ngọc Bích', '翡翠盔')
add_map('Mũ Phượng Hoàng', '凤凰盔')
add_map('Mũ Thần Long', '神龙盔')
add_map('Mũ Thiết Ma', '铁魔盔')
add_map('Mũ Chí Tôn', '至尊盔')
add_map('Mũ Thái Bình', '太平盔')
add_map('Mũ Ánh Trăng', '月华盔')
add_map('Mũ Thuật Sĩ', '术士盔')
add_map('Mũ Phục Ma', '伏魔盔')
add_map('Mũ Thần Thoại', '神话盔')
add_map('Mũ Anh Vũ', '鹦鹉盔')
add_map('Mũ Chiêm Tinh', '占星盔')
add_map('Mũ Quyền Lực', '权力盔')
add_map('Mũ Huyết Long', '血龙盔')
add_map('Mũ Bạch Long', '白龙盔')
add_map('Mũ Ma Vương', '魔王盔')
add_map('Mũ Hoàng Long', '皇龙盔')
add_map('Mũ Thiên Vũ', '天羽盔')
add_map('Mũ Quỷ Vương', '鬼王盔')
add_map('Mũ Bạch Hổ', '白虎盔')
add_map('Mũ Lụa', '丝盔')
add_map('Áo Vải Thô', '粗布衣')
add_map('Áo Thiên Kim', '千金衣')
add_map('Áo Lụa', '丝绸衣')
add_map('Áo Phượng Hoàng', '凤凰衣')
add_map('Áo Lôi Phong', '雷风衣')
add_map('Áo Quyền Năng', '权能衣')
add_map('Áo Ánh Trăng', '月华衣')
add_map('Áo Hoàng Kim', '黄金衣')
add_map('Áo Ma Pháp', '魔法衣')
add_map('Áo Nữ Vương', '女王衣')
add_map('Áo Bóng Ma', '魅影衣')
add_map('Áo Anh Vũ', '鹦鹉衣')
add_map('Áo Chiêm Tinh', '占星衣')
add_map('Áo Quyền Lực', '权力衣')
add_map('Áo Bạch Long', '白龙衣')
add_map('Quần Xương', '骨腿')
add_map('Quần Nhân Sư', '狮身腿')
add_map('Quần Trinh Nữ', '处女腿')
add_map('Quần Ngọc Bích', '翡翠腿')
add_map('Quần Ma Vương', '魔王腿')
add_map('Quần Chí Tôn', '至尊腿')
add_map('Quần Thái Bình', '太平腿')
add_map('Quần Hỏa Thiên', '火天腿')
add_map('Quần Bão Điện', '电暴腿')
add_map('Quần Hoàng Long', '皇龙腿')
add_map('Quần Thiên Vũ', '天羽腿')
add_map('Quần Quỷ Vương', '鬼王腿')
add_map('Quần Bạch Hổ', '白虎腿')
add_map('Găng Đồng', '铜手套')
add_map('Găng Ma Thuật', '魔法手套')
add_map('Găng Trâu Xanh', '青牛手套')
add_map('Găng Thiết Phiến', '铁扇手套')
add_map('Găng Thiên Thanh', '天青手套')
add_map('Găng Phong Vũ', '风雨手套')
add_map('Găng Triệu Hồn', '召魂手套')
add_map('Găng Thần Long', '神龙手套')
add_map('Găng Thánh Nữ', '圣女手套')
add_map('Găng Hắc Vương', '黑王手套')
add_map('Găng Thần Ma', '神魔手套')
add_map('Găng Thái Dương', '太阳手套')
add_map('Găng Nữ Thần', '女神手套')
add_map('Găng Thuật Sĩ', '术士手套')
add_map('Găng Phục Ma', '伏魔手套')
add_map('Tay Thần Thoại', '神话手')
add_map('Tay Đế Vương', '帝王手')
add_map('Giầy Vải Thô', '粗布靴')
add_map('Giầy Thiên Kim', '千金靴')
add_map('Giầy Lụa', '丝绸靴')
add_map('Giầy Phượng Hoàng', '凤凰靴')
add_map('Giầy Lôi Phong', '雷风靴')
add_map('Giầy Quyền Năng', '权能靴')
add_map('Giầy Ánh Trăng', '月华靴')
add_map('Giầy Hoàng Kim', '黄金靴')
add_map('Giầy Ma Pháp', '魔法靴')
add_map('Giầy Nữ Vương', '女王靴')
add_map('Giầy Bóng Ma', '魅影靴')
add_map('Giầy Anh Vũ', '鹦鹉靴')
add_map('Giầy Chiêm Tinh', '占星靴')
add_map('Giầy Quyền Lực', '权力靴')
add_map('Giầy Bạch Long', '白龙靴')
add_map('Cánh Thiên Đàng', '天堂翼')
add_map('Cánh Linh Hồn', '灵魂翼')
add_map('Cánh Cuồng Phong', '狂风翼')
add_map('Cánh Lôi Vũ', '雷羽翼')
add_map('Cánh Hỏa Thiên', '火天翼')
add_map('Cánh Cô Độc Nhỏ', '小孤独翼')
add_map('Cánh Quỷ Nhỏ', '小鬼翼')
add_map('Cánh Tiên Nữ Nhỏ', '小仙女翼')
add_map('Cánh Thiên Đàng Nhỏ', '小天堂翼')
add_map('Cánh Hỗn Nguyên (2.5)', '混沌翼(2.5)')
add_map('Cánh Ma Thuật (2.5)', '魔法翼(2.5)')
add_map('Cánh Hỏa Thần (2.5)', '火神翼(2.5)')
add_map('Cánh Chinh Phục', '征服翼')
add_map('Áo Choàng Nhỏ Lord', '小领主披风')
add_map('Áo Choàng Nhỏ RF', '小RF披风')
add_map('Áo Choàng Tử Thần (2.5', '死神披风(2.5)')
add_map('Cánh Cấp 4 - DW', '4级翼-DW')
add_map('Cánh Cấp 4 - DK', '4级翼-DK')
add_map('Cánh Cấp 4 - ELF', '4级翼-ELF')
add_map('Cánh Cấp 4 - SM', '4级翼-SM')
add_map('Cánh Cấp 4 - MG', '4级翼-MG')
add_map('Cánh Cấp 4 - DL', '4级翼-DL')
add_map('Cánh Cấp 4 - SU', '4级翼-SU')
add_map('Cánh Cấp 4 - RF', '4级翼-RF')
add_map('Cánh Cấp 4 - EF', '4级翼-EF')
add_map('Nhẫn Băng', '冰戒指')
add_map('Nhẫn Gió', '风戒指')
add_map('Nhẫn Phù Thủy', '巫师戒指')
add_map('Nhẫn Mặt Trăng', '月亮戒指')
add_map('Nhẫn Giáng Sinh', '圣诞戒指')
add_map('Nhẫn Người Tuyết', '雪人戒指')
add_map('Nhẫn Ngọc Bích', '翡翠戒指')
add_map('Nhẫn Thạch Anh Tím', '紫水晶戒指')
add_map('Nhẫn Thánh Thần (A)', '圣神戒指(A)')
add_map('Nhẫn Thánh Thần (B)', '圣神戒指(B)')
add_map('Nhẫn Tim Bạc (A)', '银心戒指(A)')
add_map('Nhẫn Tim Bạc (B)', '银心戒指(B)')
add_map('Dây Chuyền Gió', '风项链')
add_map('Dây Chuyền Ngọc Bích', '翡翠项链')
add_map('Dây Chuyền Thánh Thần', '圣神项链')
add_map('Dây Chuyền Tim Bạc', '银心项链')
add_map('Giáp Hỗn Nguyên', '混沌甲')
add_map('Giáp Hung Thần', '凶神甲')
add_map('Mảnh Vỡ Áo Giáp', '铠甲碎片')
add_map('Bùa Thiên Sứ', '天使护符')
add_map('Bùa Hộ Thân', '护身符')
add_map('Bùa Cánh Quỷ', '鬼翼护符')
add_map('Bùa Cánh Vũ Linh', '羽灵翼护符')
add_map('Bùa Cánh Linh Hồn', '灵魂翼护符')
add_map('Bùa Cánh Bóng Đêm', '暗夜翼护符')
add_map('Bùa Kết Hợp Chaos', '混沌合成护符')
add_map('Bùa Tăng HP', '增加HP护符')
add_map('Bùa Phòng Thủ', '防御护符')
add_map('Bùa Maple', '枫叶护符')
add_map('Bùa Về Thành', '回城护符')
add_map('Nước Thánh', '圣水')
add_map('Lông Vũ Condor', '神鹰羽毛')
add_map('Reset Thể Lực', '重置体力')
add_map('Búa Thiên Sứ', '天使锤')
add_map('Búa Archangels', '大天使锤')
add_map('Thư Triệu Tập', '召集书')
add_map('Móng Ngựa Cũ', '旧马蹄铁')
add_map('Ngọc Chém Xoáy', '旋转斩宝石')
add_map('Ngọc Tăng Tấn Công', '增加攻击宝石')
add_map('Ngọc Đâm Xoáy', '旋转刺宝石')
add_map('Ngọc Chém Lửa', '火斩宝石')
add_map('Ngọc Đâm Gió', '风刺宝石')
add_map('Ngọc Liên Hoàn Tiễn', '连射宝石')
add_map('Ngọc Ước Nguyện', '许愿宝石')
add_map('Ngọc Cấp Độ', '等级宝石')
add_map('Ngọc Kỹ Năng', '技能宝石')
add_map('Ngọc May Mắn', '幸运宝石')
add_map('Ngọc Tính Năng', '功能宝石')
add_map('Ngọc Hoàn Hảo', '完美宝石')
add_map('Ngọc Socket', '镶嵌宝石')
add_map('Ngọc Thần', '神之宝石')
add_map('Ngọc Full', '满宝石')
add_map('Ngọc Nâng Cấp', '升级宝石')
add_map('Ngọc RingPen', '指环宝石')
add_map('Đá Tạo Hóa', '造化石')
add_map('Sừng Quỷ Vương', '魔王角')
add_map('Rượu Tết', '春节酒')
add_map('Thần tượng', '神像')
add_map('Hoa Anh Đào Trắng', '白樱花')
add_map('Chiến Binh Danh Dự', '荣誉战士')
add_map('Mãnh Tướng', '猛将')
add_map('Key 30 Ngày', '30天钥匙')
add_map('Key Điểm 90 Ngày', '90天积分钥匙')
add_map('Gói Quà B', '礼包B')
add_map('Gói Quà E', '礼包E')
add_map('Rương Cũ', '旧宝箱')
add_map('Rương VIP', 'VIP宝箱')
add_map('Rương Thức Tỉnh', '觉醒宝箱')
add_map('Rương Mắt Xanh', '蓝眼宝箱')
add_map('Rương Hắc Thần', '黑神宝箱')
add_map('Rương Thánh Thần', '圣神宝箱')
add_map('Rương Tim Bạc', '银心宝箱')
add_map('Vé Đặc biệt', '特殊门票')
add_map('Vé Tham Gia Dopple', '参加双倍门票')
add_map('Bình Máu Nhỏ', '小生命药水')
add_map('Bình Phép Nhỏ', '小魔法药水')
add_map('Bình SD Vừa', '中SD药水')
add_map('Bình Thuốc Vừa', '中药剂')
add_map('Bình HP Cao Cấp', '高级HP药水')
add_map('Thuốc Nhanh Nhẹn', '敏捷药剂')
add_map('Bức Thư Quỷ', '鬼信')
add_map('Nước Mắt Tiên Nữ', '精灵之泪')
add_map('Dấu Hiệu Đổi Tên', '改名标记')
add_map('Cường Hóa Goblin', '哥布林强化')
add_map('Hộp Quà Vàng', '金色礼盒')
add_map('Hộp Quà Tím', '紫色礼盒')
add_map('Hộp Châu báu', '珠宝盒')
add_map('Quà bất ngờ', '惊喜礼物')
add_map('Pháo Hoa Noel', '圣诞烟花')
add_map('Lucky Mũ Ticket', '幸运帽券')
add_map('Lông Vũ Season 5', '羽毛 Season5')
add_map('Ngọc Tăng Tấn Công', '增加攻击宝石')
add_map('Đá Hộ Mệnh', '守护石')
add_map('nội lực', '内力')
add_map('hồi phục', '恢复')
add_map('quái vật', '怪物')
add_map('tăng cường', '增强')
add_map('đẩy lùi', '击退')
add_map('mục tiêu', '目标')
add_map('chống lại', '抵抗')
add_map('hiệu ứng', '效果')
add_map('cơ hội', '机会')
add_map('chí mạng', '致命一击')
add_map('nữ hoàng', '女王')
add_map('làng', '村庄')
add_map('khu vực', '区域')
add_map('Ma Pháp', '魔法')
add_map('Hấp thụ', '吸收')
add_map('Nguyên Liệu Kết Hợp Cánh Cấp 3', '3级翅膀合成材料')
add_map('Nguyên Liệu Kết Hợp Cánh Cấp 5', '5级翅膀合成材料')
add_map('Nguyên Liệu Kết Hợp Cánh Season 8', 'Season8翅膀合成材料')
add_map('Nguyên Liệu Kết Hợp Áo Choàng 2.5', '2.5披风合成材料')
add_map('Nguyên Liệu Chế Tạo Cánh Cấp 5', '5级翅膀制作材料')
add_map('X20 Đồng Xu Đổi Nguyên Liệu Wing 2.5', 'X20金币换2.5翼材料')
add_map('Món Đồ Qúy Hiếm Không Được Bán Hoặc Vứt Đi', '稀有物品不可出售或丢弃')
add_map('Số lượng %d/10', '数量 %d/10')
add_map('i gian nhất định', '一定时间')
add_map('i phục mana', '恢复魔力')
add_map('Phục hồi HP', '恢复生命值')
add_map('Phục hồi mana', '恢复魔力')
add_map('Phục hồi hoàn toàn HP', '完全恢复生命值')
add_map('Phục hồi SD', '恢复SD')
add_map('Phục hồi tất cả SD', '恢复全部SD')
add_map('Phục hồi Stamina 100', '恢复体力100')
add_map('Tỷ lệ %0.2f%% 做 choáng mục tiêu', '眩晕目标几率%0.2f%%')
add_map('Tỷ lệ đẩy lùi mục tiêu', '击退目标几率')
add_map('Tăng tỷ lệ chống lại hiệu ứng choáng', '增加抗眩晕效果几率')
add_map('Tăng cơ hội chống lại hiệu ứng choáng', '增加抗眩晕效果机会')
add_map('Tăng Sát Thương', '增加伤害')
add_map('Tăng sức sát thương', '增加伤害力')
add_map('Tăng Tính Năng Cho Món Đồ', '增加物品功能')
add_map('Gia Cường Dòng Vàng Cho Món Đồ', '强化金色属性')
add_map('Tăng cường', '增强')
add_map('Tăng cường cột lửa', '增强火柱')
add_map('Tăng cường Mưa độc tố', '增强毒雨')
add_map('Tăng cường Lôi thạch', '增强雷石')
add_map('Mưa Băng Tuyết Master', '大师暴雪')
add_map('Tăng 力量 Wing 3', '增加力量3代翼')
add_map('Tăng 防御 Wing 3', '增加防御3代翼')
add_map('Tăng 攻击力 Gầm Thét', '增加咆哮攻击力')
add_map('Giảm hao mòn 武器', '减少武器磨损')
add_map('Giảm hao mòn', '减少磨损')
add_map('Tăng sức 伤害 chí mạng', '增加致命伤害')
add_map('Tăng lực 攻击 魔法', '增加魔法攻击力')
add_map('Tăng 魔法力 当 带 gậy', '装备法杖时增加魔力')
add_map('Tăng 伤害 hoàn hảo', '增加完美伤害')
add_map('Tăng 伤害 Bóng Ma', '增加魅影伤害')
add_map('Tăng 伤害 Lửa', '增加火焰伤害')
add_map('Tăng 伤害 Chém Xoáy', '增加旋转斩伤害')
add_map('Tăng 伤害 Chém Sức Mạnh', '增加力量斩伤害')
add_map('Tăng 伤害 phép', '增加魔法伤害')
add_map('Tăng 伤害 phép sét', '增加雷魔法伤害')
add_map('Tăng 伤害 phép TTLH', '增加TTLH魔法伤害')
add_map('Tăng 伤害 的 gậy 1 tay', '增加单手杖伤害')
add_map('Tăng cường hấp thụ 伤害 的 翅膀', '增加翅膀伤害吸收')
add_map('Tăng cường hấp thụ 伤害 当 带 Cánh Phượng Hoàng', '装备凤凰翼时增加伤害吸收')
add_map('Hấp thụ sức 伤害', '吸收伤害')
add_map('Hấp thụ 20%% sức 伤害', '吸收20%伤害')
add_map('Tăng 30%% 攻击力, Phép thuật', '增加30%攻击力,魔法')
add_map('ng lực tấn công thấp nhất', '最低攻击力')
add_map('ng lực tấn công cao nhất', '最高攻击力')
add_map('Giảm 30%% sức 伤害 的 quái vật', '减少怪物30%伤害')
add_map('Tỷ lệ 伤害 hoàn hảo', '完美伤害几率')
add_map('Tăng 20%% 伤害 chí mạng', '增加20%致命伤害')
add_map('Tăng 7%% sức 伤害', '增加7%伤害')
add_map('Tăng 10%% sức 伤害', '增加10%伤害')
add_map('Tăng %d%% sức 伤害', '增加%d%%伤害')
add_map('Tăng 防御 %0.2f', '增加防御%0.2f')
add_map('Tăng %0.2f nội lực', '增加内力%0.2f')
add_map('Tăng 攻击力 %0.2f', '增加攻击力%0.2f')
add_map('Tăng Năng Lượng stat', '增加能量属性')
add_map('Tăng Sức Mạnh stat', '增加力量属性')
add_map('Tăng 力量 攻击', '增加力量攻击')
add_map('Chúc 你 chơi game vui vẻ', '祝你游戏愉快')
add_map('Tăng %d Nhanh nhẹn', '增加%d敏捷')
add_map('Tăng %d Mệnh lệnh', '增加%d统率')
add_map('Để Nâng Cấp VIP 12 thành VIP 13', '升级VIP12至VIP13')
add_map('Để Nâng Cấp VIP 15 thành VIP 16', '升级VIP15至VIP16')
add_map('Để Nâng Cấp Set 400 Thành Bộ Huyết Thần', '升级400套为血神套')
add_map('Kháng Độc: %d', '抗毒: %d')
add_map('Kháng Đất: %d', '抗地: %d')
add_map('Vào Kalima miễn phí', '免费进入卡利玛')
add_map('Thể lực 需求: %d', '体力需求: %d')
add_map('Cấp độ 需求: %d', '等级需求: %d')
add_map('Thuộc tính', '属性')
add_map('Nguyên Liệu Set Hiệp Sĩ', '骑士套装材料')
add_map('Tăng 攻击力 Pet', '增加宠物攻击力')
add_map('Tăng %% phép thuật', '增加%%魔法')
add_map('Tăng %% nguyền rủa', '增加%%诅咒')
add_map('Không bao gồm các item CashShop', '不包括商城物品')
add_map('Mũi 名', '尖刺名称')
add_map('n sách ế Vương', '帝王之书')
add_map('ang sử dụng giảm', '使用中减少')
add_map('ng Nước Xanh', '绿水波')
add_map('Sấm sét', '雷霆')
add_map('Đâm ánh sáng', '光刺')
add_map('Gầm Thét', '咆哮')
add_map('Chém xoáy lên', '上旋斩')
add_map('c xoáy', '旋转')
add_map('Lượng nước', '水量')
add_map('Lửa Địa Ngục', '地狱火')
add_map('a Xích Long', '赤龙')
add_map('a đòn chí mạng', '致命一击')
add_map('g Sát Thương', '伤害')
add_map('n trượng', '法杖')
add_map('c độ 攻击', '攻击速度')
add_map('giới hạn', '限制')
add_map('i đa', '最大')
add_map('i gian hồi 1 phút', '冷却1分钟')
add_map(' 使用 lại 后 5s', '使用后5秒')
add_map('trong', '在')
add_map('Vô hiệu', '无效')
add_map('Lực 1 tay:', '单手攻击力:')
add_map('Lực 2 tay:', '双手攻击力:')
add_map('Sức kháng phép:', '魔法抗性:')
add_map('Sức đánh Ma pháp', '魔法攻击力')
add_map('Cấp kỹ năng', '技能等级')
add_map('Điểm dư', '剩余点数')
add_map('Nội lực', '内力')
add_map('Lượng Sinh lực', '生命值')
add_map('Sức chống đỡ', '抵挡力')
add_map('Sức chống phép', '魔法抗性')
add_map('Khả năng phòng vệ', '防御能力')
add_map('Tự động phục hồi', '自动恢复')
add_map('Khả năng đánh Ma pháp', '魔法攻击能力')
add_map('Khả năng sử dụng khi chuyển động', '移动时可用')
add_map('Zen có thể chuyển hóa thành Rena', '金币可转换为Rena')
add_map('Kho đồ', '仓库')
add_map('Sửa toàn bộ', '全部修理')
add_map('Phí sửa chữa', '修理费')
add_map('Phí giữ đồ', '保管费')
add_map('Gửi tiền', '存钱')
add_map('Sửa chữa', '修理')
add_map('Bắt đầu nhắn tin nhắn riêng', '开始发送私信')
add_map('Không nhận tin nhắn riêng', '不接受私信')
add_map('Thông tin Nhóm', '队伍信息')
add_map('Giải tán', '解散')
add_map('Đã hết cung tên', '箭已用完')
add_map('ng đất,', '地面')
add_map('n thú', '猛兽')
add_map('m vụ', '任务')
add_map(' làng ?', '村庄?')
add_map('ử dụng.', '使用.')
add_map('  vào khu vực 这', ' 进入该区域')
add_map('Lính Giáo', '枪兵')
add_map('Cấm địa Hoàng gia', '皇家禁地')
add_map('Quảng Trường Quỷ', '恶魔广场')
add_map('Hỗn Nguyên Lâu', '混沌城堡')
add_map('Sức phòng vệ', '防御力')
add_map('Đặt trước: công việc', '预设: 职业')
add_map('Tăng %d HP #Tăng %d Mana', '增加%d生命 #增加%d魔力')
add_map('#Giảm Sát Thương: 2%%', '#减少伤害: 2%%')
add_map('#Sát Thương: +40%%', '#伤害: +40%%')
add_map('#Tốc Độ Đánh: +40', '#攻击速度: +40')
add_map('#Tốc Độ Đánh: +60', '#攻击速度: +60')
add_map('#Tốc Độ Đánh: +90', '#攻击速度: +90')
add_map('#Tốc Độ Đánh: +120', '#攻击速度: +120')
add_map('#Kinh Nghiệm Tăng 70%%', '#经验增加70%%')
add_map('#Kinh Nghiệm Tăng 100%%', '#经验增加100%%')
add_map('#Kinh Nghiệm Tăng 130%%', '#经验增加130%%')
add_map('#Tăng HP/MP Tăng: 15.000', '#增加HP/MP: 15000')
add_map('#Tăng HP/MP Tăng: 30.000', '#增加HP/MP: 30000')
add_map('#Tăng HP/MP Tăng: 45.000', '#增加HP/MP: 45000')
add_map('Tăng Tính Năng Cho Món Đồ', '增加物品属性')
add_map('Gia Cường Dòng Vàng Cho Món Đồ', '强化金色属性')
add_map('g x3 Sát Thương 3%%', '3倍伤害3%%')
add_map('món này', '此物品')
add_map('Dùng cho', '适用于')
add_map('Giá mua', '购买价格')
add_map('Giá bán', '出售价格')
add_map('Không thể quăng món đồ này', '无法丢弃此物品')
add_map('Bạn không thể sử dụng', '你不能使用')
add_map('Nếu ném ra đất sẽ có phần thưởng', '扔到地上会有奖励')
add_map('Chỉ rớt một loại vật phẩm', '只掉落一种物品')
add_map('Cách sử dụng các phím Nút chức năng', '功能键使用方法')
add_map('Tìm gặp NPC Trao đổi', '找NPC交换')
add_map('Tăng Tính Năng Cho Món Đồ', '增加物品功能')
add_map('Gia Cường Dòng Vàng Cho Món Đồ', '强化金色属性')
add_map('Sách thuộc tính 1', '属性书 1')
add_map('Sách thuộc tính 2', '属性书 2')
add_map('Sách thuộc tính 3', '属性书 3')
add_map('Sách thuộc tính 4', '属性书 4')
add_map('Sách thuộc tính 5', '属性书 5')
add_map('Sách thuộc tính 6', '属性书 6')
add_map('Ý chí mạnh mẽ', '坚强意志')
add_map('Tăng cường cột lửa', '增强火柱')
add_map('Tăng cường Mưa độc tố', '增强毒雨')
add_map('Tăng cường Lôi thạch', '增强雷石')
add_map('Mưa Băng Tuyết Master', '大师暴雪')
add_map('Bão Ánh Sáng', '光之暴风')
add_map('Biến hình', '变形')
add_map('Sét', '闪电')
add_map('Phép thuật +20', '魔法 +20')
add_map('Kháng Độc', '抗毒')
add_map('Kháng Đất', '抗地')
add_map('ghi nhớ vị trí', '记住位置')
add_map('Vuốt Thiên Tử', '天子爪')
add_map('Sách Bóng Ma', '魅影之书')
add_map('Chim Băng', '冰鸟')
add_map('Chim Lửa', '火鸟')
add_map('Tă最低攻击力', '增加最低攻击力')
add_map('Tă最高攻击力', '增加最高攻击力')
add_map('Tă攻击力', '增加攻击力')
add_map('TăSD防御力', '增加SD防御力')
add_map('i 盔甲 trụ 同 类', '在盔甲同类中')
add_map('g đâm xoáy', '旋转刺')
add_map(' Công %0.2f%%', '攻击%0.2f%%')
add_map('chiêu', '技能')


# ============================================================
# Sorted keys for substring matching (longest first)
# ============================================================
sorted_vn_keys = sorted(VN_CN_MAP.keys(), key=len, reverse=True)
# Pre-compiled regex patterns for case-insensitive matching
compiled_patterns = [(re.compile(re.escape(k), re.IGNORECASE), VN_CN_MAP[k]) for k in sorted_vn_keys]

# ============================================================
# UTILITY FUNCTIONS
# ============================================================

def xor_transform(data, length=None):
    if length is None:
        length = len(data)
    result = bytearray(data)
    lim = min(length, len(result))
    for i in range(lim):
        result[i] ^= KEY[i % 3]
    return bytes(result)

def decode_bmd_bytes(data):
    """Try to decode bytes as UTF-8 then GBK, return (str, encoding)"""
    for enc in ('utf-8', 'gbk'):
        try:
            s = data.decode(enc)
            if '�' not in s:
                return s, enc
        except:
            pass
    return data.decode('utf-8', errors='replace'), 'utf-8'

def find_strings(data, min_len=3):
    strings = []
    start = -1
    for i in range(len(data)):
        b = data[i]
        if b >= 0x20 and b != 0x7F:
            if start == -1:
                start = i
        else:
            if start != -1 and i - start >= min_len:
                raw = bytes(data[start:i])
                s, _ = decode_bmd_bytes(raw)
                if any(c.isalnum() or ord(c) > 0x80 for c in s):
                    strings.append((start, i, s))
            start = -1
    if start != -1 and len(data) - start >= min_len:
        raw = bytes(data[start:])
        s, _ = decode_bmd_bytes(raw)
        if any(c.isalnum() or ord(c) > 0x80 for c in s):
            strings.append((start, len(data), s))
    return strings

def translate_string(s):
    """Translate VN/EN string to Chinese using dictionary (case-insensitive matching)"""
    result = s
    for pattern, replacement in compiled_patterns:
        result = pattern.sub(replacement, result)
    return result

def has_vn_chars(s):
    return bool(re.search(r'[àáạãăèéẹẽêìíịĩòóọõôơùúụũưừừửữựđ]', s))

def has_only_ascii(s):
    return all(0x20 <= ord(c) <= 0x7E for c in s)

def count_vn_lines(lines):
    """Count lines with VN text"""
    count = 0
    for line in lines:
        # Extract text between quotes
        qs = line.find('"')
        qe = line.rfind('"')
        if qs != -1 and qe > qs:
            text = line[qs+1:qe]
            if has_vn_chars(text):
                count += 1
    return count

# ============================================================
# FILE TRANSLATORS
# ============================================================

def rebuild_item_bmd(bmd_path):
    """Translate Item_CHN.bmd using Item.txt + custom translations"""
    name = os.path.basename(bmd_path)
    print(f'\n[{name}]')

    cn_names = {}
    with open(ITEM_TXT, 'r', encoding='utf-8') as f:
        lines = f.readlines()
    ct, si, ins = -1, 0, False
    for line in lines:
        ls = line.strip()
        if not ls or ls.startswith('//'): continue
        if ls == 'end': ins = False; si = 0; continue
        if ls.isdigit(): ct = int(ls); ins = True; si = 0; continue
        if not ins: continue
        parts = ls.split('\t')
        if len(parts) >= 9:
            m = re.search(r'"([^"]*)"', parts[8])
            if m and m.group(1).strip():
                flat = ct * 512 + si
                if flat < 8192: cn_names[flat] = m.group(1).strip()
        si += 1

    with open(bmd_path, 'rb') as f:
        raw = f.read()
    data_end = min(84 * 8192, len(raw))
    decrypted = bytearray(xor_transform(raw, data_end))

    cn_count = 0
    custom_count = 0
    for idx in range(8192):
        offset = idx * 84
        if offset + 30 > data_end: break
        nb = bytes(decrypted[offset:offset+30])
        null_pos = nb.find(b'\x00')
        if null_pos == -1: null_pos = 30

        name_to_write = None
        if idx in cn_names:
            name_to_write = cn_names[idx]
            cn_count += 1
        elif null_pos > 0:
            current_name = nb[:null_pos].decode('utf-8', errors='replace')
            translated = translate_string(current_name)
            if translated != current_name:
                name_to_write = translated
                custom_count += 1

        if name_to_write:
            encoded = name_to_write.encode('gbk', errors='replace')
            max_len = min(len(encoded), 29)
            decrypted[offset:offset+max_len] = encoded[:max_len]
            if max_len < 30:
                decrypted[offset+max_len:offset+30] = b'\x00' * (30 - max_len)

    encrypted = xor_transform(bytes(decrypted), data_end)
    with open(bmd_path, 'wb') as f:
        f.write(encrypted)
        if len(raw) > data_end:
            f.write(raw[data_end:])
    print(f'  Item.txt: {cn_count} | Custom: {custom_count}')


def translate_text_txt_format(txt_path):
    """Translate a TXT file in format: index \"text\" or index\\tnumber\\t\"text\""""
    name = os.path.basename(txt_path)
    print(f'\n[{name}]')

    # Read with encoding detection
    with open(txt_path, 'rb') as f:
        raw = f.read()

    binary_lines = raw.split(b'\n')
    lines = []
    for bl in binary_lines:
        bl = bl.rstrip(b'\r')
        try:
            lines.append(bl.decode('utf-8'))
        except:
            try:
                lines.append(bl.decode('gbk'))
            except:
                lines.append(bl.decode('latin-1'))

    # Count VN lines
    vn_total = count_vn_lines(lines)
    translated = 0
    new_lines = []

    for line in lines:
        qs = line.find('"')
        qe = line.rfind('"')
        if qs != -1 and qe > qs:
            prefix = line[:qs+1]
            suffix = line[qe:]
            text = line[qs+1:qe]
            new_text = translate_string(text)
            if new_text != text:
                translated += 1
            new_lines.append(f'{prefix}{new_text}{suffix}\n')
        else:
            new_lines.append(line + '\n')

    # Write back
    with open(txt_path, 'w', encoding='utf-8') as f:
        f.writelines(new_lines)
    print(f'  VN lines: {vn_total} | Translated: {translated}')


def patch_bmd_from_txt(bmd_path, txt_path):
    """Apply translations from TXT file to corresponding BMD file"""
    name = os.path.basename(bmd_path)
    print(f'  BMD patch: {name}')

    # Read TXT to get all translated strings by position
    txt_translations = {}
    with open(txt_path, 'r', encoding='utf-8') as f:
        txt_lines = f.readlines()

    for line in txt_lines:
        qs = line.find('"')
        qe = line.rfind('"')
        if qs != -1 and qe > qs:
            text = line[qs+1:qe].strip()
            if text:
                txt_translations[text] = translate_string(text)

    # Read and decrypt BMD
    with open(bmd_path, 'rb') as f:
        raw = bytearray(f.read())

    decrypted = bytearray(xor_transform(raw, len(raw)))

    # Find strings and translate
    strings = find_strings(bytes(decrypted))
    patched = 0
    for start, end, s in strings:
        translated = translate_string(s)
        if translated != s:
            old_raw = bytes(decrypted[start:end])
            old_len = len(old_raw.rstrip(b'\x00'))
            new_bytes = translated.encode('gbk', errors='replace')
            if len(new_bytes) <= old_len:
                padding = b'\x00' * (old_len - len(new_bytes))
                decrypted[start:start+old_len] = new_bytes + padding
                patched += 1

    if patched > 0:
        encrypted = xor_transform(bytes(decrypted), len(raw))
        with open(bmd_path, 'wb') as f:
            f.write(encrypted)
    print(f'  Patched BMD strings: {patched}')


def translate_bmd_direct(bmd_path):
    """Translate strings directly in a BMD file"""
    name = os.path.basename(bmd_path)
    print(f'\n[{name}]')

    with open(bmd_path, 'rb') as f:
        raw = f.read()

    decrypted = bytearray(xor_transform(raw, len(raw)))
    strings = find_strings(bytes(decrypted))

    vn_count = sum(1 for _, _, s in strings if has_vn_chars(s))
    print(f'  Strings: {len(strings)} (VN: {vn_count})')

    if vn_count == 0 and not any('SOLAR' in s for _, _, s in strings):
        print(f'  -> Skip')
        return

    patched = 0
    for start, end, s in strings:
        if not has_vn_chars(s) and not has_only_ascii(s):
            continue
        translated = translate_string(s)
        if translated == s:
            continue
        old_raw = bytes(decrypted[start:end])
        old_len = len(old_raw.rstrip(b'\x00'))
        new_bytes = translated.encode('gbk', errors='replace')
        if len(new_bytes) <= old_len:
            padding = b'\x00' * (old_len - len(new_bytes))
            decrypted[start:start+old_len] = new_bytes + padding
            patched += 1

    if patched > 0:
        encrypted = xor_transform(bytes(decrypted), len(raw))
        with open(bmd_path, 'wb') as f:
            f.write(encrypted)

    print(f'  Patched: {patched}')


# ============================================================
# MAIN
# ============================================================
def main():
    print('=' * 60)
    print('CHN 文件夹 BMD 翻译工具')
    print(f'词典条目: {len(VN_CN_MAP)}')
    print('=' * 60)

    # Phase 1: TXT source files
    print('\n--- Phase 1: TXT source files ---')
    txt_files = [
        'Text_CHN.txt',
        'ItemTooltipText_CHN.txt',
    ]
    for fname in txt_files:
        path = os.path.join(CHN_DIR, fname)
        if os.path.exists(path):
            translate_text_txt_format(path)

    # Phase 2: Item_CHN.bmd (special format)
    print('\n--- Phase 2: Item_CHN.bmd ---')
    item_bmd = os.path.join(CHN_DIR, 'Item_CHN.bmd')
    if os.path.exists(item_bmd):
        rebuild_item_bmd(item_bmd)

    # Phase 3: BMD files with TXT sources
    print('\n--- Phase 3: BMD from TXT sources ---')
    bmd_txt_pairs = [
        ('Text_CHN.bmd', 'Text_CHN.txt'),
        ('ItemTooltipText_CHN.bmd', 'ItemTooltipText_CHN.txt'),
    ]
    for bname, tname in bmd_txt_pairs:
        bpath = os.path.join(CHN_DIR, bname)
        tpath = os.path.join(CHN_DIR, tname)
        if os.path.exists(bpath) and os.path.exists(tpath):
            patch_bmd_from_txt(bpath, tpath)

    # Phase 4: Direct BMD translation
    print('\n--- Phase 4: Direct BMD translation ---')
    direct_bmds = [
        'ItemLevelTooltip_CHN.bmd',
        'ItemTooltip_CHN.bmd',
        'JewelOfHarmonyOption_CHN.bmd',
        'JewelOfHarmonySmelt_CHN.bmd',
        'MasterSkillTooltip_CHN.bmd',
        'QuestWords_CHN.bmd',
        'Quest_CHN.bmd',
        'Dialog_CHN.bmd',
        'skill_CHN.bmd',
        'socketitem_CHN.bmd',
        'slide_CHN.bmd',
    ]
    for fname in direct_bmds:
        path = os.path.join(CHN_DIR, fname)
        if os.path.exists(path):
            translate_bmd_direct(path)

    print(f'\n{"="*60}')
    print('完成！')
    print(f'{"="*60}')


if __name__ == '__main__':
    main()
