use [MuOnline]

delete from AccountCharacter
delete from CashLog
delete from CashShopData
delete from CashShopInventory
delete from CashShopPeriodicItem
delete from Character
delete from CustomAttack
delete from CustomGift
delete from CustomItemBank
delete from CustomJewelBank
delete from CustomNpcQuest
delete from CustomQuest
delete from DataNapGame
delete from EquipInventory
delete from EventLeoTheHelper
delete from EventSantaClaus
delete from ExtWarehouse
delete from Gens_Duprian
delete from Gens_Rank
delete from Gens_Rank
delete from Gens_Reward
delete from Gens_Varnert
delete from Guild
delete from GuildMember
delete from HelperData
delete from ItemLog
delete from ItemMarketData
delete from LOG_CREDITOS
delete from LuckyCoin
delete from LuckyItem
delete from Marry
delete from MasterSkillTree
delete from MEMB_INFO
delete from MEMB_STAT
delete from MK_Server
delete from MuCastle_DATA
delete from MuCastle_MONEY_STATISTICS
delete from MuCastle_NPC
delete from MuCastle_REG_SIEGE
delete from MuCastle_REG_SIEGE
delete from MuCastle_SIEGE_GUILDLIST
delete from OptionData
delete from QuestKillCount
delete from QuestWorld
delete from RankingDevilSquare
delete from RankingBloodCastle
delete from RankingChaosCastle
delete from RankingDuel
delete from RankingIllusionTemple
delete from RankingKingGuild
delete from RankingKingPlayer
delete from RankingTvT
delete from T_CGuid
delete from T_FriendList
delete from T_FriendMail
delete from T_FriendMain
delete from T_PetItem_Info
delete from T_WaitFriend
delete from warehouse
delete from WarehouseGuild
delete from WZ_CW_INFO
update GameServerInfo set ItemCount = 0