[AutoNapBank]
Enable = 1
;Liên hệ nhà cung cấp Server để Setup
APIAutoCheckBank = AKfycbzPglfZQGtxiBiIFT-X1WiR7eVdcoq9hwmaqfPZUpHdso5RWRNabQ0jzAeIXcngXlzg4w
;TypeDB = 0 Dữ liệu ghi vào DataNapGame, tự cộng Wcoin trực tiếp
;TypeDB = 1 Thì khi nạp sẽ ghi vào CardPhone theo WebVWeb, khi kiểm tra đã CK thì sẽ cộng gcoin
TypeDB = 0
;Tỷ lệ wcoin/gcoin nhận được so với giá trị nạp vào
TyleNapTien = 100
;Tiền nạp ít nhất
GiaTriNapThapNhat= 10000
;Thông báo toàn server sau khi auto check nạp thành công
EnableThongBao = 1
MsgThongBao= "[%s] vùa nạp thành công %s VND"
;Time huỷ thanh toán , VD = 5 thì sau 5 phút nếu không member không quét QR chuyển khoản thì lệnh này sẽ huỷ bỏ (giảm lượt request api)
; = 0 thì không set
; Lưu ý : huỷ thanh toán vẫn nằm trong lịch sử thanh toán, chỉ chuyển sang trạng thái huỷ
HuyThanhToan=30