[AntihackConfig]
;Config AntihackClient
LoadAntihack = 0
AntihackServerPort = 55858
AntihackServerName = MUKEN.SITE
GSPortMin=55901
GSPortMax=55999
;ShowMessageBox = 1 检测到外挂时显示消息框而非Logo位图 
ShowMessageBox = 0

[MainInfo]
; LauncherType
; 1: Check Launcher theo WindowName
; 2: Check Launcher theo Mutex : #32770,vvv
LauncherType = 0
LauncherName = Autoupdate
LauncherFile = Launcher.exe
CustomerName = takumi12
IpAddress = 197.159.75.59
IpAddressPort = 63000
ClientVersion = 1.04.05
ClientSerial = TbYehR2hFUPBKgZj
WindowName = [-MU-]
ScreenShotPath = ScreenShots\Screen(%02d_%02d-%02d-%02d)-%04d.jpg
ClientName = Main.exe
GTM 			  = 7
PluginName        = 
CameraName        = 
;==================================================
;Giao Dien Interface
; 0 = Season 6
; 1 = Season 2
; 3 = Season Ex700
IsSeason          = 0
;==================================================
;Show Info Item Drop 在地面上
ShowInfoItemDrop          = 0

[HelperInfo]
HelperActiveAlert = 1
HelperActiveLevel = 10

[CharacterInfo]
DWMaxAttackSpeed  = 67000
DKMaxAttackSpeed  = 67000
FEMaxAttackSpeed  = 67000
MGMaxAttackSpeed  = 67000
DLMaxAttackSpeed  = 67000
SUMaxAttackSpeed  = 67000
RFMaxAttackSpeed  = 67000

[ReconnectInfo]
ReconnectTime     = 0
[Custom]
;==================================================
;在普通地图使用CTC技能
;注意: 需要GS支持！
;==================================================
EnableCsSkillsAllMaps = 1

;==================================================
; Player System Options
; 0 = Disabled
; 1 = Enabled
;==================================================
PlayerShowName = 1
PlayerShowGuildLogo = 1
;==================================================
FpsMonitor = 1
FpsLimit = 120

;游戏功能开关
Menu0	=	1 //事件时间
Menu1	=	1 //购买VIP
Menu2	=	1 //排行榜
Menu3	=	1 //变性
Menu4	=	1 //自由市场
Menu5	=	1 //称号
Menu6	=	0 //充值
Menu7	=	1 //宝石银行
Menu8	=	0 //VIP角色
Menu9	=	1 //洗卓越属性
Menu10	=	1 //修改密码
Menu11	=	1 //充值里程碑
Menu12	=	0 //锁物品
Menu13	=	0 //锁物品
;==================================================
;充值卡银行信息
Bank_NameBank	="970422"								
Bank_STK		="666888"						
Bank_ChuTK		="TEN BAN"						
Bank_ChiNhanh	="MBBank"		
;==================================================
EnableButtonFB = 1
LinkFacbook = "https://facebook.com"
ViTriFB_X = 35
ViTriFB_Y = 435
;==================================================
EnableButtonZL = 1
LinkZalo= "https://zalo.me/"

ViTriZL_X = 5
ViTriZL_Y = 435
;==================================================
; 开启/关闭宠物栏
; 0: 关闭
; 1: 开启
EnableSlotPet = 1
ShowCommandInfo = 1
OnBangChiSo = 1
;0 Off, 1 原始样式(显示在怪物头上), 2 瞄准怪物时显示在中间
OnHealBar = 1
;==================================================
; 删除角色
; 0: 默认
; 1: 删除Sum/Dl/Rf
; 2: 删除Sum, Rf
; 3: 删除Rf
;==================================================
RemoveClass = 2
;==================================================
; 开启/关闭380合成
; 0: 开启
; 1: 关闭
;==================================================
DisableMix380 = 0
;==================================================
; 血色城堡 - 恶魔广场等级
;==================================================
MaxLevelBlood    		= 8
MaxLevelDevil    		= 7
;==================================================
; 3D摄像机缩放限制
ZoomMin = 15
ZoomMax = 65
;==================================================
;开启/关闭自动HP
EnableButtonAutoHP = 0
DelayAutoHP = 100
RateHP = 100
ViTriAutoHP_X = 122
ViTriAutoHP_Y = 408
;==================================================
;开启/关闭自动重置
EnableButtonRS = 1
ViTriRS_X = 165
ViTriRS_Y = 409
;==================================================
;开启/关闭自动PK
EnableButtonAutoPK = 1
ViTriAutoPK_X = 108
ViTriAutoPK_Y = 409
;==================================================
;隐藏宠物
隐藏宠物IsDW 	= 1
隐藏宠物IsDK 	= 1
隐藏宠物IsELF 	= 1
隐藏宠物IsMG 	= 1
隐藏宠物IsDL 	= 1
隐藏宠物IsSUM 	= 1
隐藏宠物IsRF 	= 1
隐藏宠物Delay = 5000
